export const ASTNODE_TYPE = {
  BLOCK: "BLOCK",
  BINARY_OPERATOR: "BINARY_OPERATOR",
  UNARY_OPERATOR: "UNARY_OPERATOR",
  VARIABLE: "VARIABLE",
  EXPRESSION: "EXPRESSION",
  IF_STATEMENT: "IF_STATEMENT",
  ELSE_STATEMENT: "ELSE_STATEMENT",
  FOR_STATEMENT: "FOR_STATEMENT",
  ASSIGN_STATEMENT: "ASSIGN_STATEMENT",
  FUNCTION_DECLARE_STATEMENT: "FUNCTION_DECLARE_STATEMENT",
  SCALAR: "SCALAR",
} as const;

export type ASTNODE_TYPE = (typeof ASTNODE_TYPE)[keyof typeof ASTNODE_TYPE];
