export const ASTNODE_TYPE = {
  BLOCK: "BLOCK",
  BINARY_OPERATOR: "BINARY_OPERATOR",
  UNARY_OPERATOR: "UNARY_OPERATOR",
  VARIABLE: "VARIABLE",
  EXPRESSION: "EXPRESSION",
  IF_STATEMENT: "IF_STATEMENT",
  ELSE_STATEMENT: "ELSE_STATEMENT",
  FOR_STATEMENT: "FOR_STATEMENT",
  WHILE_STATEMENT: "WHILE_STATEMENT",
  ASSIGN_STATEMENT: "ASSIGN_STATEMENT",
  VARIABLE_DECLARE_STATEMENT: "VARIABLE_DECLARE_STATEMENT",
  RETURN_STATEMENT: "RETURN_STATEMENT",
  FUNCTION_DECLARE_STATEMENT: "FUNCTION_DECLARE_STATEMENT",
  FUNCTION_ARGS_STATEMENT: "FUNCTION_ARGS_STATEMENT",
  SCALAR: "SCALAR",
  PROGRAM: "PROGRAM",
} as const;

export type ASTNODE_TYPE = (typeof ASTNODE_TYPE)[keyof typeof ASTNODE_TYPE];

export const OPERATOR_BINDING_POWER = {
  "==": [1, 2],
  "+": [10, 11],
  "-": [10, 11],
  "*": [20, 21],
  "/": [20, 21],
} as const;

export type OPERATOR_BINDING_POWER = (typeof OPERATOR_BINDING_POWER)[keyof typeof OPERATOR_BINDING_POWER];
